apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: pricelist-postdeploy
  namespace: pricelist
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          until [ $(curl -s -o /dev/null -w "%{http_code}" http://pricelist:8080) -eq 200 ]; do echo "waiting for app to start"; sleep 5; done
          curl -s http://pricelist:8080/create_database.php
        image: quay.io/redhatworkshops/pricelist:latest
        name: pricelist-postdeploy
        resources: {}
      restartPolicy: Never
