mysql:
  ###architecture: "replication"
  architecture: "standalone"
  serviceAccount:
    name: "pricelist-db"
  auth:
    database: "pricelist"
    username: "pricelist"
    password: "pricelist"
  ###secondary: 
    ###replicaCount: "2"
