apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: pricelist-presync
  namespace: pricelist
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          /usr/local/bin/maint-script.sh
        image: quay.io/redhatworkshops/pricelist-maint:latest
        name: pricelist-presync
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "1Gi"
            cpu: "1"
      restartPolicy: Never
