apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: pricelist-cd-temp
  namespace: pricelist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricelist
      tier: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pricelist
        tier: frontend
    spec:
      containers:
        image: quay.io/redhatworkshops/pricelist:latest
        imagePullPolicy: Always
        name: pricelist
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 512m
            memory: 512Mi
      restartPolicy: Always
