apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pricelist
    tier: frontend
  name: pricelist
  namespace: pricelist
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricelist
      tier: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pricelist
        tier: frontend
    spec:
      containers:
      - image: quay.io/redhatworkshops/pricelist-maint:latest
        name: pricelist
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: MYSQL_DATABASE
          value: "null"
        - name: MYSQL_PASSWORD
          value: "null"
        - name: MYSQL_USER
          value: "null"
        - name: MYSQL_SERVICE_HOST
          value: "null"
        - name: MYSQL_SERVICE_PORT
          value: "0000"
